FROM openjdk:19-jdk-alpine
WORKDIR /usr/lib
ADD ./target/UserAuthenticatonService-0.0.1-SNAPSHOT.jar /usr/lib/UserAuthenticatonService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","UserAuthenticatonService-0.0.1-SNAPSHOT.jar"]